theme = 'hugo-blog-awesome'

[[params.socialIcons]]
name = "github"
url = "https://github.com/alexshook"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/alexshook"

[[params.socialIcons]]
name = "Rss"
url = "index.xml"
