theme = 'hugo-blog-awesome'
baseurl = "http://alexshook.com"
title = "Alex Shook"
languageCode = "en-us"

MetaDataFormat = "toml"
paginate = 10

[menu]
  [[menu.main]]
    # The page reference (pageRef) is useful for menu highlighting
    # When pageRef is set, setting `url` is optional; it will be used as a fallback if the page is not found.
    pageRef="/"
    name = 'Home'
    url = '/'
    weight = 10
  [[menu.main]]
    pageRef="post"
    name = 'Posts'
    url = '/post/'
    weight = 20
  [[menu.main]]
    pageRef="projects"
    name = 'Projects'
    url = '/projects/'
    weight = 30
  [[menu.main]]
    pageRef="about"
    name = 'About'
    url = '/about/'
    weight = 30

[params]
  sitename = "Alex Shook"
  defaultColor = "dark" # set color mode: dark, light, auto
  # Setting it to 'auto' applies the color scheme based on the visitor's device color preference.If you don't specify anything, ignore this parameter, or leave it blank,
  # the default value is set to 'auto'.
  # You can take a look at layouts/index.html for more information.
  description = "code and stuff"
  # mainSections = ['posts']
  toc = false # set to false to disable table of contents 'globally'
  goToTop = true # set to false to disable 'go to top' button
  # additionalScripts = ['js/custom.js', 'js/custom-2.js']
  # Will try to load 'assets/js/custom.js' and 'assets/js/custom-2.js'.
  # Your custom scripts will be concatinated to one file `custom.js`.
  # When building for production it will be minified.
  # The file `custom.js` is loaded on each page (before body tag ends).

[params.author]
  # avatar = "avatar.jpg" # put the file in assets folder; also ensure that image has same height and width
  # Note: image is not rendered if the resource(avatar image) is not found. No error is displayed.
  intro = "Alex Shook"
  name = "Alex Shook"
  description = "code and stuff"

[author]
  name = "Alex Shook"

[permalinks]
  # Optional. Change the permalink format for the 'post' content type.
  # The format shown here is the same one Jekyll/Octopress uses by default.
  post = "/:title/"


[[params.socialIcons]]
name = "github"
url = "https://github.com/alexshook"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/alexshook"

[[params.socialIcons]]
name = "Rss"
url = "index.xml"
